# Generated by Django 5.1.4 on 2025-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_count', models.IntegerField(default=0, verbose_name='Tap Count')),
                ('full_name', models.TextField(verbose_name='Full Name')),
                ('rank', models.CharField(max_length=20, verbose_name='Rank')),
                ('profile_pic', models.FileField(upload_to='pfp/', verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
            },
        ),
    ]
