# Generated by Django 5.1.4 on 2025-01-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_ranks_alter_user_id_alter_user_profile_pic_user_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranks',
            options={'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='pfp/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.ranks', verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tap_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tap Count'),
        ),
    ]
